# generic compiler flags
CFLAGS = -O3
LFLAGS = -framework OpenGL -framework GLUT

# NVCC flags
COMMA       = ,
EMPTY       =
SPACE       = $(EMPTY) $(EMPTY)
CUDA_PATH   = /Developer/GPU\ Computing/C
NVCC_CFLAGS = -m64 -I$(CUDA_PATH)/common/inc \
              -Xcompiler $(subst $(SPACE),$(COMMA),$(CFLAGS)) # -Xptxas -v
NVCC_LFLAGS = -L$(CUDA_PATH)/lib -lcutil_x86_64 \
              $(CUDA_PATH)/common/lib/darwin/libGLEW.a \
              -Xlinker $(subst $(SPACE),$(COMMA),$(LFLAGS))
